name: lionpuro.com.dev
services:
  workspace:
    environment:
      PORT: "3000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "/app/tools/wgo.sh"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
