FROM golang:1.24.1

ARG UID=1000
ARG GID=1000

RUN groupadd -g ${GID} developer && \
	useradd -l -u ${UID} -g developer developer && \
	mkdir /home/developer

WORKDIR /app

RUN apt-get update && \
	apt-get upgrade -y && \
	apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
	apt-get install -y nodejs build-essential

RUN chown -R ${UID}:${GID} /home/developer /go
USER developer

CMD ["/app/tools/wgo.sh"]
