name: lionpuro.com
networks:
  caddy:
services:
  server:
    env_file: ".env"
    image: lionpuro/lionpuro.com:latest
    ports:
      - "3000"
    networks:
      - caddy
  caddy:
    build:
      context: .
      dockerfile_inline: |
        FROM caddy:latest
        COPY Caddyfile /etc/caddy/Caddyfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    networks:
      - caddy
