package blog

import "github.com/alecthomas/chroma/v2"

func customTheme() *chroma.Style {
	return chroma.MustNewStyle("custom-github", chroma.StyleEntries{
		chroma.Error:                  "#e6edf3",
		chroma.LineHighlight:          "bg:#6e7681",
		chroma.LineNumbers:            "#6e7681",
		chroma.Background:             "#e6edf3 bg:#242424",
		chroma.Keyword:                "#fc697f",
		chroma.KeywordConstant:        "#79c0ff",
		chroma.KeywordPseudo:          "#79c0ff",
		chroma.Name:                   "#e6edf3",
		chroma.NameClass:              "#b3d6ff",
		chroma.NameConstant:           "#79c0ff",
		chroma.NameDecorator:          "#bfadf5",
		chroma.NameEntity:             "#ffa657",
		chroma.NameException:          "#f0883e",
		chroma.NameFunction:           "#bfadf5",
		chroma.NameLabel:              "#79c0ff",
		chroma.NameNamespace:          "#fc697f",
		chroma.NameProperty:           "#79c0ff",
		chroma.NameTag:                "#88bfff",
		chroma.NameVariable:           "#79c0ff",
		chroma.Literal:                "#a5d6ff",
		chroma.LiteralDate:            "#79c0ff",
		chroma.LiteralStringAffix:     "#79c0ff",
		chroma.LiteralStringDelimiter: "#79c0ff",
		chroma.LiteralStringEscape:    "#79c0ff",
		chroma.LiteralStringHeredoc:   "#79c0ff",
		chroma.LiteralStringRegex:     "#79c0ff",
		chroma.Operator:               "#e77485",
		chroma.Comment:                "italic #8b949e",
		chroma.CommentSpecial:         "italic #8b949e",
		chroma.CommentPreproc:         "#8b949e",
		chroma.Generic:                "#e6edf3",
		chroma.GenericDeleted:         "#ffa198 bg:#490202",
		chroma.GenericEmph:            "italic",
		chroma.GenericError:           "#ffa198",
		chroma.GenericHeading:         "bold #79c0ff",
		chroma.GenericInserted:        "#56d364 bg:#0f5323",
		chroma.GenericOutput:          "#8b949e",
		chroma.GenericPrompt:          "#8b949e",
		chroma.GenericStrong:          "bold",
		chroma.GenericSubheading:      "#79c0ff",
		chroma.GenericTraceback:       "#ff7b72",
		chroma.GenericUnderline:       "underline",
		chroma.TextWhitespace:         "#6e7681",
		chroma.Punctuation:            "#8b949a",
		chroma.KeywordType:            "#79c0ff",
	})
}
